"""add_contact_fields

Revision ID: 771cf4a3a84f
Revises: 5eb0e850bbf2
Create Date: 2025-12-15 12:57:31.644403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771cf4a3a84f'
down_revision: Union[str, Sequence[str], None] = '5eb0e850bbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeker_profiles', sa.Column('contact_phone', sa.Text(), nullable=True))
    op.add_column('seeker_profiles', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeker_profiles', 'age')
    op.drop_column('seeker_profiles', 'contact_phone')
    # ### end Alembic commands ###
